language: python

python:
    - "2.7"

install:
    - "pip install -r requirements.txt --use-mirrors"


#script: tox
script: python setup.py install
after success: python testcode.py
notifications:
    email: false