language: python

python:
    - "2.7"

install:
    - "pip install -r requirements.txt --index-url"

script: python setup.py install

after_success: python testcode.py

notifications:
    email: false