language: python

python:
    - "2.7"

env:
  - TOXENV=py27
  - TOXENV=py33


install:
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install tox"

script: tox

notifications:
    email: false